In [1]:
import numpy as np

In [2]:
def rms(original_frames, filtered_frames):
  return np.sqrt(((original_frames - filtered_frames) ** 2).mean())

In [7]:
original = np.asarray([
  [
    [2,2,2],
    [1,1,1],
    [1,1,1],
  ],
  [
    [1,1,1],
    [1,1,1],
    [1,1,1],
  ]
])

filtered = np.asarray([
  [
    [0,1,0],
    [0,1,0],
    [0,1,0],
  ],
  [
    [0,0,0],
    [1,1,1],
    [0,0,0],
  ]
])


In [9]:
diff =  original - filtered
print('diff', diff)

pow = np.power(diff, 2)
print('pow', pow)

mean = np.mean(pow)
print('mean', mean)

sqrt = np.sqrt(mean)
print('sqrt', sqrt)

print('rms', rms(original, filtered))

diff [[[2 1 2]
  [1 0 1]
  [1 0 1]]

 [[1 1 1]
  [0 0 0]
  [1 1 1]]]
pow [[[4 1 4]
  [1 0 1]
  [1 0 1]]

 [[1 1 1]
  [0 0 0]
  [1 1 1]]]
mean 1.0555555555555556
sqrt 1.0274023338281628
rms 1.0274023338281628


In [27]:
np.power((original - filtered), 5)

array([[[32,  1, 32],
        [ 1,  0,  1],
        [ 1,  0,  1]],

       [[ 1,  1,  1],
        [ 0,  0,  0],
        [ 1,  1,  1]]], dtype=int32)